### ISSUE TITLE
Add a release engine for npm

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#489]
This is part of our overarching goal of supporting more package managers in Keygen: https://github.com/keygen-sh/keygen-api/issues/493.

Implement similar to #478. I think I’d prefer a `node` or `npm` subdomain. See #679 for implementation of PyPI, and #753 for 
Tauri. The Tauri one will likely be the most helpful for reference, since the PyPI included a lot of noisy ground work.

Helpful resources:

- https://keygen.sh/blog/how-to-license-and-distribute-commercial-node-modules/
- https://github.com/keygen-sh/example-private-npm-package

This engine is meant to replace the workflow in that blog post — it should be a turn-key way to distribute modules.

In the end, I want a customer to be able to upload a module (e.g. via `npm pack`) to the distribution API we already have, and allow their end-users to `npm install` that module like they would from https://npmjs.com.

Implementation should include [integration tests](https://github.com/keygen-sh/keygen-api/blob/master/features/api/v1/engines/tauri/v2/upgrade.feature). lmk of any questions.

**Comment by ezekg** [comment]
What makes this hard is that npm's [package abbreviated manifest](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-metadata-format) requires `dependency` data, and I don't want to add one-off functionality to the API to treat `package.json` artifacts as "special."

The simplest route here would be to require additional fields like `dependencies`, `devDependencies`, `peerDependencies`, `bin`, etc. be supplied in the `package.json` artifact's metadata. This approach aligns with what we do for PyPI artifact metadata as well, e.g. `data-requires-python`.

**Comment by ezekg** [comment]
Helpful article on the API expected by npm and friends: https://keygen.sh/blog/how-to-license-and-distribute-commercial-node-modules/. We can use that to model the npm engine here.

**Comment by rajeshj11** [comment]
@varshith257 I would like to collaborate with you. If you're interested, please let me know how I can assist.

**Comment by ezekg** [comment]
Thought it may be helpful to see how others do it: https://github.com/KN4CK3R/gitea/blob/4b1f387cb90e15d0f1659b96df6a283f98c65438/routers/api/packages/api.go#L304-L348

**Comment by ezekg** [comment]
> What makes this hard is that npm's [abbreviated package manifest](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-metadata-format) requires `dependency` data, and we don't have artifact blobs to pull that data from (blobs are uploaded to the storage provider after the redirect). And I don't want to add one-off functionality to the API to treat `package.json` artifacts as "special."
> 
> The simplest route here would be to require additional fields like `dependencies`, `devDependencies`, `peerDependencies`, `bin`, etc. be supplied in the `package.json` artifact's metadata. We can add a baseline per the required properties like `name`, `version`, `dist`, while pulling the rest from `metadata`. The `time` field also looks to be used by [Unity's package manager](https://docs.unity3d.com/Manual/Packages.html) (which seems based on the npm spec), so we should include that too.
> 
> This approach aligns with what we do for [PyPI artifact metadata](https://github.com/keygen-sh/keygen-api/blob/master/app/views/api/v1/release_engines/pypi/simple/show.html.haml#L15) as well, e.g. `data-requires-python`.
> 
> Publishing via the CLI (see also: [keygen-sh/keygen-cli#13](https://github.com/keygen-sh/keygen-cli/issues/13)):
> 
> ```shell
> keygen upload package.json --release 1.0.0 --metadata "$(cat package.json |  jq 'del(.name, .version)')"
> ```
> 
> Every registry has their own quirks. 🤪

I actually think I want to go a different route here, since Rubygems looks like it needs the dependency data, and we can't just throw that into release `metadata` like we can with npm: https://github.com/keygen-sh/keygen-api/pull/896#pullrequestreview-2355498136

The idea is that we set up a processing job pipeline for release metadata artifacts, such as an npm `package.json` or a Rubygems gemspec. Ultimately, this would allow us to store release metadata locally in a `release_metadata` table, allowing deeper integrations with package managers, while reducing reliance on S3/R2 for obtaining said metadata.

This approach also avoids weird quirks which come from shoehorning resource `metadata`  to fit this purpose like I originally proposed above (and like we currently do with PyPI via the `data-` attributes ). A proper pipeline will allow us to expand into other package managers, regardless of metadata format.
