### ISSUE TITLE
Add a release engine for Rubygems

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#491]
This is part of our overarching goal of supporting more package managers in Keygen: https://github.com/keygen-sh/keygen-api/issues/493.

See #679 for implementation of PyPI, and #753 for Tauri. Bulk of the PyPI logic is in [the controller](https://github.com/keygen-sh/keygen-api/blob/master/app/controllers/api/v1/release_engines/pypi/simple_controller.rb), with integration tests [here](https://github.com/keygen-sh/keygen-api/blob/master/features/api/v1/engines/pypi/simple/index.feature) and [here](https://github.com/keygen-sh/keygen-api/blob/master/features/api/v1/engines/pypi/simple/show.feature). The Tauri implementation can be found in the aforementioned PR, since it's much simpler than the PyPI PR, as the PR for PyPI contained a lot of ground work for future packaging systems and may not be particularly helpful.

Implementation-wise here, we need to implement the expected [API for Rubygems](https://github.com/KN4CK3R/gitea/blob/4b1f387cb90e15d0f1659b96df6a283f98c65438/routers/api/packages/api.go#L368-L378), in a way that's compatible with Keygen's existing distribution schema. May be able to use [the Rubygems lib](https://github.com/rubygems/rubygems) for heavy lifting here, but I'm not sure. Like PyPI and Tauri, the implementation should only be concerned with downloading gems, not uploading. Drafting releases and uploading artifacts to Keygen's distribution API can be done via [Keygen's CLI](https://keygen.sh/docs/cli/), or via the Dashboard.

For an overview on the API endpoints expected by Rubygems, check out this blog post: https://keygen.sh/blog/how-to-license-and-distribute-a-private-rubygem/. We can use that to model the Rubygems engine here. This engine is meant to replace the workflow in that blog post — it should be a turn-key way to distribute gems.

In the end, I want a customer to be able to upload a `.gem` file (via `gem build`) to the distribution API we already have, and allow their end-users to `gem install` that gem like they would from https://rubygems.org.

Implementation should include [integration tests](https://github.com/keygen-sh/keygen-api/blob/master/features/api/v1/engines/tauri/v2/upgrade.feature). lmk of any questions.

**Comment by mobley-trent** [comment]
Currently configuring my environment... Will it be easier if docker-compose support is integreted first @ezekg ?

**Comment by ezekg** [comment]
@mobley-trent We're working on that in #727 but no ETA yet.

**Comment by josefarias** [comment]
I'm traveling this week, so commenting prematurely to be in the loop.

I've got my env set up, tests passing, and I'm familiar with the rubygems implementation so I'm optimistic I can get this done when I'm back.

/attempt #491

**Comment by josefarias** [comment]
Sorry about the noise, turns out I'll be quite busy when I get back. Canceling my attempt as I won't be able to get to it. Hopefully next time!
