### ISSUE TITLE
Add request timing and headers to request logs

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#519]
E.g. `Content-Type`, `Content-Length` and `Accept` request headers, and `Content-Type` and `Content-Length` response headers. The `Authorization` header MUST NOT be included, of course. Timings may be able to be derived from the `X-Request-Start` header or something from Rails' internals (since Rails internally keeps timings on various things).

Add 2 new `jsonb` columns, `request_logs.request_headers` and `request_logs.response_headers`. Add the additional arguments to the request log Sidekiq job, taking consideration into the process [for safely changing a job's arguments](https://keygen.sh/blog/how-to-change-the-signature-of-a-sidekiq-job/).

Ref: https://github.com/discourse/discourse/blob/1472e47aae5bfdfb6fd9abfe89beb186c751f514/lib/middleware/request_tracker.rb

**Comment by ashutosh887** [comment]
I'll take this forward @ezekg

**Comment by ezekg** [comment]
Sure, @ashutosh887. You've picked up a few issues now, so looking forward to the PRs.
