### ISSUE TITLE
Add Keygen-* request/response headers to request logs

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#628]
E.g. `Keygen-Signature`, `Keygen-Version`, etc. Add 2 new `jsonb` columns, `request_logs.request_headers` and `request_logs.response_headers`.

**Comment by ezekg** [comment]
Related to #519.

**Comment by ashutosh887** [comment]
Let me try this @ezekg

**Comment by ezekg** [comment]
@ashutosh887 go ahead.
