### ISSUE TITLE
Allow draft artifacts to be downloaded by admins

### ISSUE THREAD

**Issue by mgd722** [keygen-sh/keygen-api#740]
To reproduce:
- make a draft release
- upload an artifact
- navigate to that artifact's page and click "Download"
- you will arrive at an API endpoint displaying json

Solutions:
- disable download button on artifacts when their release is a draft
- allow artifact downloads to work with draft releases

I'd lean towards the latter. It'd be useful to be able to review the content of a draft release before publishing it, especially if you weren't the author of the release.

**Comment by ezekg** [comment]
The ability to download draft artifacts is now available in Keygen Cloud.
