### ISSUE TITLE
Always respond Not found error

### ISSUE THREAD

**Issue by MoonTTMM** [keygen-sh/keygen-api#759]
I have self hosted a server following the doc. The ping and health api works fine. But other api just respond Not found.
There's log on keygen's console like: 
`method=POST path=/v1/accounts/foobar/tokens format=jsonapi controller=ErrorsController action=show status=404`

This is my request:
```
  curl -X POST https://<foodomain>/v1/accounts/foorbar/tokens \
  -H 'Accept: application/vnd.api+json' \
  -u "email:password"
```

**Comment by ezekg** [comment]
You most likely didn't configure the `KEYGEN_HOST` environment variable correctly. It should be set to the domain name you're accessing Keygen under, e.g. `licensing.example.com`.

Regardless, you should be able to forego the `/accounts/<account>` prefix. I.e. `/v1/accounts/foobar/tokensm` would become `/v1/tokens`.

**Comment by MoonTTMM** [comment]
Thanks, /v1/tokens works.
Do not see any doc mentioned that.
