### ISSUE TITLE
Fix vulnerabilities from used libraries

### ISSUE THREAD

**Issue by MarkusGnigler** [keygen-sh/keygen-api#769]
We have a customer requirement that all high and critical vulnerabilities on our used components should be fixed.
I would like to ask if updating all affected libraries would be possible?

The used scanner is [trivy](https://github.com/aquasecurity/trivy) and it's easily reproducible with `docker run --rm aquasec/trivy image keygen/api:latest`

![image](https://github.com/keygen-sh/keygen-api/assets/82930719/bcbefbd8-bb16-4f11-abff-e61cbb8b1296)

Kind regards

**Comment by ezekg** [comment]
Please do not use GitHub issues to report vulnerabilities. Instead follow our vulnerability reporting procedure: [`SECURITY.md`](https://github.com/keygen-sh/keygen-api/blob/master/SECURITY.md). Many of these are not applicable to the project, simply due to the fact the vulnerable code is not used.

**Comment by MarkusGnigler** [comment]
It was more a question of whether it was possible to update the libraries, not a concrete vulnerability.

The question remains, is it possible to update at least the libraries with a critical CVE?

Thanks for your quick replay!

**Comment by ezekg** [comment]
Yes. You can build the [Dockerfile](https://github.com/keygen-sh/keygen-api/blob/master/Dockerfile) yourself to pull in the latest dependencies. We follow [a semiannual release schedule](https://keygen.sh/docs/self-hosting/#versioning) for our self-hosted API, and security updates of dependencies are included in those releases every 6 months.

**Comment by MarkusGnigler** [comment]
Thanks for the hint. I guess i can wait for a new release.

Just for my understanding:
I'm not sure if this is fixable in the dockerfile. Are the library versions not be defined in the gem file?

**Comment by ezekg** [comment]
Please report these to security@keygen.sh and we can continue discussion there.
