### ISSUE TITLE
question on offline licensing : machine specific 

### ISSUE THREAD

**Issue by pawangh** [keygen-sh/keygen-api#772]
Hello All, 
We intend to use keygen to generate offline licensing. We intend to create license file unique to machine. 
Is it possible in keygen ? 

Thanks
Pawan

**Comment by ezekg** [comment]
Yes, you'll want to [checkout a machine](https://keygen.sh/docs/api/machines/#machines-actions-check-out), which will result in a machine file. License files and machine files share a lot of similarities in overall format, but they differ in the data that is embedded inside them. A license file contains a signed and encrypted license object — the license being checked out. While a machine file contains a signed and encrypted machine object — the machine being checked out. In addition, when encrypted, license files are encrypted with the license's key, while machine files are encrypted with the license's key and the machine's fingerprint. Additional relationship data can be included in both, e.g. a machine file can also include its related license object.
