### ISSUE TITLE
Display real-time license information in an external dashboard.

### ISSUE THREAD

**Issue by ayntk-ai** [keygen-sh/keygen-api#786]
Can I display real-time information such as:
1. license usage
2. number 8/100 users/ uses --> license key limited to users
3. users who have logged in with the license key
4. Expiration date
5. Renewal date
6. Cancellation date
7. additional license key information
8. Daily limit
9. ...

**Comment by ezekg** [comment]
Issues are for feature requests and bugs only, not questions. Please ask questions in [the Discord](https://discord.gg/TRrhSaWSsN) or [discussion forum](https://github.com/keygen-sh/community/discussions).
