### ISSUE TITLE
Restrict license keys to specific users or a specific number of users

### ISSUE THREAD

**Issue by ayntk-ai** [keygen-sh/keygen-api#787]
1. How can I limit license keys to a specific user, username, user email or user ID?
2. How can I limit license keys to a certain number of registered users --> e.g. the license key is valid for 20 users --> 20 different users can register with this key after which no more users can register with the key but the key is still valid for the subscription period?

**Comment by ezekg** [comment]
In the future, issues are for feature requests and bugs only, not questions. Please ask other questions in [the Discord](https://discord.gg/TRrhSaWSsN) or [discussion forum](https://github.com/keygen-sh/community/discussions). But you can lock a license to a specific user via [a user-locked license](https://keygen.sh/docs/). For multi-user licenses, that will be available with multi-user licensing in #774 (not released yet). Right now, licenses are single-user only.

**Comment by ayntk-ai** [comment]
When will be the release?

**Comment by ezekg** [comment]
No definite timeline. The PR is still under review.
