### ISSUE TITLE
Tauri engine always return 204 with no content in the response body

### ISSUE THREAD

**Issue by lucabrini** [keygen-sh/keygen-api#834]
I've setupped Keygen Cloud with all products, releases, packages, licences needed.

I've uploaded binaries and attached them to releases as well. Published them. However the tauri engine endpoint used for auto updates does return only 204 with an empty body, even if a more recent artifact is present.

May I am missing some setting but I think the docs could be a lot better than now, at least for tauri side.

**Comment by ezekg** [comment]
Can you provide a request log that shows this behavior?

**Comment by ezekg** [comment]
I found your account. It looks like [you're trying to upgrade from v0.1.1 to v1.0.0](https://app.keygen.sh/request-logs/1e4b587d-0384-4b3b-a5a7-d8c5d373c332), but v1.0.0 has no artifacts, so it's not available for upgrade. So v0.1.1 is effectively the latest version, which is the current version, thus there is no upgrade available.

This is what I've been able to grok from the current releases and artifacts on your account after looking at your recent request logs. If you think this is incorrect, please provide more information. Be specific. Request logs are very helpful.

**Comment by lucabrini** [comment]
- I'm using License authentication
- I'm actually trying to upgrade from 0.1.0-dev to 0.1.1-dev (as shown in the log you linked)
- I'm expecting `alba.app.tar.gz`
- Platform/arch is darwin/x86_64

**Comment by ezekg** [comment]
But if v1.0.0 exists and is published, why would it upgrade from v0.1.0 to v0.1.1? When I looked, v1.0.0 was the latest published version, not v0.1.1. Also, why is v1.0.0 published without any artifacts?

**Comment by ezekg** [comment]
But if v1.0.0-dev exists and is published, why would it upgrade from v0.1.0-dev to v0.1.1-dev? When I looked, v1.0.0-dev was the latest published version, not v0.1.1-dev.

Also, why is v1.0.0-dev published without any artifacts? Just trying to understand everything.

**Comment by lucabrini** [comment]
Thank youuuu, now all makes sense.

So it always try to upgrade to the newest release found. Makes sense!

In the case the release has no artifact associated, may the api could return some error? Or are there any reasons about how it is now?

Thank you a lot, I appreciate you help! :)

**Comment by ezekg** [comment]
@lucabrini what's your use case for publishing a release with no artifacts?

**Comment by lucabrini** [comment]
No specific use case. It was just a mistake 🥲
