### ISSUE TITLE
Is there any way to enroll multiple licenses on one machine?

### ISSUE THREAD

**Issue by ahnjs1987** [keygen-sh/keygen-api#844]
Since a machine may have more than one license and may be added, I am wondering if there is a way to add/change more than one license to the machine.

**Comment by ezekg** [comment]
By default, the same fingerprint can be activated for multiple licenses, given the policy has [a uniqueness strategy](https://keygen.sh/docs/api/policies/#policies-object-attrs-machineUniquenessStrategy) that allows for that, but actual machine objects are per-license and managed per-license, i.e. activations are managed individually for each license as opposed to collectively. What's your use case here? Why would a machine have more than 1 license?

**Comment by ahnjs1987** [comment]
Because I can install multiple software on machine. And I want to configure different policies and license for each software, and I want those software licenses to be tied to the machine.
I think the uniqueness strategy is right for us. However, that property does not seem to be able to express dependency with a specific machine. (It is possible to compare using fingerprints, but I considered about changing group for a specific machine and software mounted on the machine.)
