### ISSUE TITLE
Faster CI?

### ISSUE THREAD

**Issue by crohr** [keygen-sh/keygen-api#845]
Hi @ezekg, I read a fair bit about Keygen and especially the [introduction of the license](https://keygen.sh/blog/all-your-licensing-are-belong-to-you/), because I'm also developing a self-hosted software ([RunsOn](https://runs-on.com)) and I had to go through the same thoughts.

In the end I chose to keep some parts of the code as closed-source, only available under a sponsorship license, but at some point I may choose the same path as you (thanks for the article).

That being said, I noticed that your CI test suite was taking almost 1h, and was wondering if you could be interested in speeding that up with RunsOn? It can be self-hosted in your AWS account and you have access to much larger runners, [with faster CPUs](https://runs-on.com/benchmarks/github-actions-runners/), and at a fraction of the cost of GitHub runners. 

Obviously since your project is now open-source you benefit from free runners from GitHub, so please ignore if you're fine with it!

Thanks :)

**Comment by ezekg** [comment]
Thanks for the offer, but at this time, I'm okay with the slow CI for the sole fact that it's free. Even on an 8 core/16 thread CPU (Ryzen 3700x), the local test suite still takes ~30 mins so I doubt there will be a significant improvement without adding considerable costs.

**Comment by crohr** [comment]
Understood, hard to compete with free!

Just as a side-note and data point for future you (maybe), a [large Rails open-source project](https://github.com/opf/openproject) was able to bring their CI time for rspec down to ~13min (from close to 2h original runtime) by using machines with 32 CPUs, for about $7/day (they have ~10 developers).
