### ISSUE TITLE
Replace null_association lib with gem

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#879]
As part of our [week of Open Source](https://x.com/_m27e/status/1823029064372031586), we extracted the internal [`null_association`](https://github.com/keygen-sh/keygen-api/blob/82adaeb9537ab5c4309d29fc4557e26a85683682/lib/null_association.rb) library into an Open Source gem: https://github.com/keygen-sh/null_association. I want to replace the internal lib with the new gem.

Including the `NullAssociation::Concern` concern is no longer required in models using `null_object:`.

Similar task to https://github.com/keygen-sh/keygen-api/pull/876.

**Comment by kaf-lamed-beyt** [comment]
/attempt #879

I'm guessing I'll just add the gem dep in `Gemfile` and run the build, then go ahead and remove the `NullAssociation::Concern` from places where it isn't needed. If that's right, kindly assign me @ezekg

**Comment by ezekg** [comment]
Yep. And as long as tests pass, we're all good.

**Comment by kaf-lamed-beyt** [comment]
Alright then... I'll get started.
