### ISSUE TITLE
Add raw distribution engine

### ISSUE THREAD

**Issue by ezekg** [keygen-sh/keygen-api#892]
Right now, the current `get.keygen.sh` subdomain doesn't really support multiple products per-account, or at least makes it hard to do so. Let's take us as an example — we have the Keygen CLI, and now we have Keygen Relay.

Versions for the CLI and Relay now conflict for a request like `get.keygen.sh/keygen/1.0.0/cli_linux_386`, since there are now multiple `1.0.0` releases — a CLI release, and a Relay release, and this URL will automatically scope to the newer release. So even when the artifact exists, it may respond with a 404 if it's scoped to the wrong `1.0.0` release i.e. Relay vs CLI.

A way forward here would be to create a "raw" engine that includes account, product, package, and release information in the URL. This way download URLs can be super specific i.r.t. scoping.

Thinking this URL pattern, making the `@<package>` scope optional ala npm:

```
GET https://raw.pkg.keygen.sh/<account>/<product>[/@<package>]/<release>/<artifact>
```

See #679 for implementation of the PyPI engine, and #753 for the Tauri engine; the Tauri one will likely be the most helpful for reference, since the PyPI included a lot of noisy ground work. But both can be good reference material.

Depends on #893.

**Comment by ezekg** [comment]
The `bin.pkg.keygen.sh` subdomain can replace `get.keygen.sh`.

**Comment by ezekg** [comment]
Currently blocking the beta release of Relay.

**Comment by ezekg** [comment]
What about this? Could work…?

```
https://raw.pkg.keygen.sh/:account/:product_or_package/:release/:artifact
```

**Comment by ezekg** [comment]
Or we could go npm-style:

```
https://raw.pkg.keygen.sh/:account/:product[/@:package]/:release/:artifact
```

**Comment by Bhavyajain21** [comment]
/attempt #892

Can I be assigned?

**Comment by ezekg** [comment]
@Bhavyajain21 go for it.
