### ISSUE TITLE
Add additional renewal basis option

### ISSUE THREAD

**Issue by lucaheft** [keygen-sh/keygen-api#902]
It would be nice to have a renewal basis option which behaves like this:
If license is still valid renew `From Expiry`.
If license is expired renew `From Now`.

Especially for extremly short living licenses `From Expiry` option has the issue that a license might be renewed but still is in Expired state.

Sample Use Case:
- Customer buys and uses license for 1 year.
- 3 Months after license is expired customer wants to renew the license.
- If the Renewal Basis is set to `From Expiry`, Customer will pay for 1 year but license is only valid for 9 more months

**Comment by ezekg** [comment]
Why doesn't `FROM_NOW` work for your example scenario? It isn't clear why a third 'combo' strategy is needed given your example scenario.

**Comment by lucaheft** [comment]
`FROM_NOW` always renews based on current time, so a license can't be renewed ahead of time.

Let's say I have a license which is valid for 1 year.
After 10 months the customer buys an additonal year.
If expiry is set to `FROM_NOW` and you would renew the license, that would mean the license is valid for 22 months overall instead of 24.

**Comment by ezekg** [comment]
Thanks for the context. Makes sense. Implemented in f187bc685fd62e4fa5b93f869ca2bd22f8251477, which introduces a `FROM_NOW_IF_EXPIRED` renewal basis.
