### ISSUE TITLE
Metadata keys get converted to camel case?

### ISSUE THREAD

**Issue by philipp-schmidt** [keygen-sh/keygen-api#916]
The following metadata
![image](https://github.com/user-attachments/assets/0740b7ab-2547-49be-ae29-46120e2389d2)
ends up being camel case in the end:
![image](https://github.com/user-attachments/assets/a45f7141-7874-423b-9082-4072bc05a0d8)

Is this intended? And can it be changed?

**Comment by ezekg** [comment]
This is documented behavior and cannot be changed: https://keygen.sh/docs/api/metadata/
