### ISSUE TITLE
Trouble setting up self-hosted

### ISSUE THREAD

**Issue by mike-5345** [keygen-sh/keygen-api#918]
Hello,

Apologies if this is the wrong place to ask.

I am a CE self-hosted user. I just launched the app using the docker compose file in the repo, first running `docker compose --profile setup run --rm setup` and then `docker compose up -d`. There were no errors reported. The only modification was changing the mapping of the caddy ports because I am running another server on the same machine: `7171:80` and `7272:443`. I set each of the non-commented environment variables in my .env file.

Running the provided ping command `curl -I http://192.168.0.11:3000/v1/ping` gives the following response:
```
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=utf-8
Location: https://192.168.0.77:3000/v1/ping
Vary: Origin
Content-Length: 0
```
Trying to hit it through the caddy server (`curl -I https://192.168.0.77:7272/v1/ping`) gives the following error, with no log showing up in the docker container output:
```
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

I am not really sure where to go from here and any help would be appreciated, even if you just point me to where I should ask this.

P.S. does the self hosted CE come with a web admin/portal? Or is it just the API?

**Comment by ezekg** [comment]
This seems like an issue with your TLS reverse-proxy, not Keygen. In addition, Keygen must be accessed via a domain name, not an IP address. This is mentioned in the self-hosting docs i.r.t. `KEYGEN_HOST`.
